services:
  twitch-drop-notifier:
    build: .
    container_name: twitch-drop-notifier
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./config.yml
        target: /config/config.yml
        read_only: true
      - drop-notifier-data:/data

volumes:
  drop-notifier-data: